### ISSUE TITLE
   polygon edge not found

### ISSUE THREAD

**Issue by kairos35** [hrbrmstr/speedtest#1]
Hi,

After successfully running the lines
`map_df(1:nrow(to_compare),` ~{ ...

trying to create a plot fails with the error message

"**Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
In addition: There were 13 warnings (use warnings() to see them)**"

Attached also a screenshot, which might include some more information.

Is this a bug or an error in the code or in my config (e.g. not enough RAM?)?
Thank for your help!
Cheers, Lucie

![screen shot 2017-11-12 at 14 09 18](https://user-images.githubusercontent.com/10060347/32699308-aaa4213a-c7b3-11e7-9e8b-5727efdce1d7.png)

**Comment by hrbrmstr** [comment]
you likely do not have the proper fonts installed. try it without the ipsum theme.

**Comment by kairos35** [comment]
Spot on - without the ipsum theme no error occurred. thanks a million
