### ISSUE TITLE
Suggestion: Choose best speed unit when displaying results

### ISSUE THREAD

**Issue by amoeba** [hrbrmstr/speedtest#2]
Hey @hrbrmstr, awesome package. I love the idea of speed testing through R but I really love how this package supports reproducible/repeatable speed testing.

I just ran a test on my amazingly fast connection (😂) and noticed the output showed my upload speed as "Upload: 0 Mbit/s" which, even though it's closer to 50kbps:

```r
> speedtest::spd_test()
Gathering test configuration information...
Gathering server list...
Determining best server...
Initiating test from GCI (24.237.15.17) to KPU Telecom / City of Ketchikan (Ketchikan, AK)

Analyzing download speed..........
Download: 1 Mbit/s

Analyzing upload speed......
Upload: 0 Mbit/s
```

I haven't looked at the source just yet but a wild guess would be that the output always uses Mbit/s or at least Mbit/s or greater units when displaying output. Is <1Mbps Internet too much of an edge case to bother trying to display a number like 50kbps instead of 0Mbps? 

I'd happily PR this of you were interested.

**Comment by hrbrmstr** [comment]
Aye. Def an oversight on my part (made a rly bad assumption). If you could PR that'd be awesome. Pls add an entry for yourself in `DESCRIPTION` as well. Thanks for catching this!

**Comment by amoeba** [comment]
Sure thing. It's not every day you engage with someone on the Internet using a 1990s speed connection.

**Comment by hrbrmstr** [comment]
Up here (rural Maine) it's far more commonplace than folks generally
expect. Also, whenever I'm on the Downeaster between Maine & Boston, the
internet is only really usable for latency-tolerant, plaintext operations
most of the time. I fondly remember my 300 baud BBS connection days :-)

**Comment by amoeba** [comment]
This was pretty straightforward. I tried to fit it and its usage best with how you've already got things done. I think it works nicely but am happy to make any changes you're interested in seeing.

I'm glad I offered to look into this because now I know about three new things:

- crayon
- purrr:safely
- %+%

**Comment by amoeba** [comment]
PS: I guessed that speedtest.net uses base 10 units in my conversions. Not sure if this is true.

**Comment by hrbrmstr** [comment]
yep that's correct.

Given my work-work (internet "stuff") `purrr::safely()` has been indispensable. 

Many thanks for a very elegant solution!

**Comment by amoeba** [comment]
Sure thing, and I appreciate you saying that!
